# A list of IP addresses: 
#   hacc-build-01: 10.1.212.110
#   alveo-u250-01: 10.253.74.12
#   alveo-u250-02: 10.253.74.16
#   alveo-u250-03: 10.253.74.20
#   alveo-u250-04: 10.253.74.24
#   alveo-u250-05: 10.253.74.28
#   alveo-u250-06: 10.253.74.40

num_FPGA : 1

CPU_IP_addr : "10.1.212.110"
# CPU_IP_addr : "127.0.0.1"
# CPU_IP_addr : "10.233.1.1" # doesn't work, firewall issue
FPGA_IP_addr_list : ["10.253.74.20"]
# FPGA_IP_addr_list : ["127.0.0.1"]
C2F_port_list: [8881]
F2C_port_list: [5001]

# Fixed parameters
# D: 128
D: NULL # determined by the dataset
ef: 64 # == ef

query_num: 10000

# Tunable parameters at runtime
batch_size: 32
max_cand_per_group: 1
max_group_num_in_pipe: 1
graph_type: "HNSW"
# graph_type: "NSG"
# dataset: NULL 
dataset: "SIFT1M"
# dataset: "SIFT10M"
# dataset: "SBERT1M"
max_degree: 64

# query window size controls the communication between CPU and FPGA
query_window_size: 100
# query_window_size: 10

# batch window size controls the speed of index scan on CPU 
batch_window_size: 3
# batch_window_size: 1